name: smile_frontend
description: Smile Front-end

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  # auth_package:
  #   git:
  #     url: https://github.com/Maua-Dev/dev_authentication.git
  #     ref: dev
  #     path: packages/auth_package
  flutter:
    sdk: flutter
  flutter_localizations:
        sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  intl: ^0.18.1
  flutter_modular: ^6.3.2
  dio: ^5.3.3
  hive_flutter: ^1.1.0
  mockito: ^5.4.2
  dartz: ^0.10.1
  flutter_mobx: ^2.1.0+1
  mobx: ^2.2.1

dev_dependencies:
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo-dev.png

scripts:
  build: flutter pub run build_runner build
  watch: flutter pub run build_runner watch --delete-conflicting-outputs

flutter_intl:
  enabled: true
