// ignore_for_file: constant_identifier_names

enum ActivityEnum {
  COURSES,
  INTERNATIONAL_WORKSHOP,
  LECTURES,
  TECHNICAL_VISITS,
  ACADEMIC_COMPETITIONS,
  HACKATHON,
  INTERNSHIP_FAIR,
  ALUMNI_CAFE,
  PROFESSORS_ACADEMY,
  CULTURAL_ACTIVITY,
  SPORTS_ACTIVITY,
  PANELS,
  MAUA_PLUS,
  ENGINEERING,
}
